# Generated by Django 5.1.7 on 2025-04-07 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_estudio', models.CharField(max_length=255)),
                ('autores', models.CharField(max_length=255)),
                ('preguntas_investigacion', models.TextField()),
                ('fuentes', models.TextField()),
                ('criterios_inclusion_exclusion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
