# Generated by Django 5.1.7 on 2025-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='criterios_inclusion_exclusion',
            new_name='cadena_busqueda',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='preguntas_investigacion',
        ),
        migrations.AddField(
            model_name='sms',
            name='anio_final',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='sms',
            name='anio_inicio',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='sms',
            name='criterios_exclusion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sms',
            name='criterios_inclusion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sms',
            name='enfoque_estudio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sms',
            name='pregunta_principal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sms',
            name='subpregunta_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='subpregunta_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='subpregunta_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='tipo_registro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sms',
            name='tipo_tecnica',
            field=models.CharField(default='', max_length=100),
        ),
    ]
