# Generated by Django 5.1.7 on 2025-04-21 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_rename_criterios_inclusion_exclusion_sms_cadena_busqueda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autores', models.TextField()),
                ('anio_publicacion', models.IntegerField()),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('enfoque', models.CharField(max_length=100)),
                ('tipo_registro', models.CharField(max_length=100)),
                ('tipo_tecnica', models.CharField(blank=True, max_length=100, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('palabras_clave', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SELECTED', 'Seleccionado'), ('REJECTED', 'Descartado'), ('PENDING', 'Pendiente')], default='PENDING', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sms.sms')),
            ],
        ),
    ]
