# Generated by Django 5.2.1 on 2025-05-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
