# Generated by Django 5.2.1 on 2025-05-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_article_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='respuesta_subpregunta_1',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta a subpregunta 1'),
        ),
        migrations.AddField(
            model_name='article',
            name='respuesta_subpregunta_2',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta a subpregunta 2'),
        ),
        migrations.AddField(
            model_name='article',
            name='respuesta_subpregunta_3',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta a subpregunta 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Revista'),
        ),
    ]
