# Generated by Django 5.2.1 on 2025-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_article_respuesta_subpregunta_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='respuesta_pregunta_principal',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta a pregunta principal'),
        ),
    ]
